export const labelConstants = {
  ABOUT_LBL: 'About',
  REGISTER_BTN: 'Register',
  LOGIN_BTN: 'Log in',
  LOGOUT_BTN: 'Log out',
  HOME_LBL: 'Home',
  MY_TEAMS_LBL: 'Teams',
  MY_GAMES_LBL: 'Games',
  SETTINGS_LBL: 'Settings',
  START_GAME_LBL: 'Start new game',
  NEW_TEAM_LBL: 'Create new team',
  EDIT_ACCOUNT_LBL: 'Edit account',
  DELETE_ACCOUNT_LBL: 'Delete account',
  SAVE_ACCOUNT_CHANGES_LBL: 'Save changes',
  CANCEL_ACCOUNT_CHANGES_LBL: 'Cancel',
  PLAYER_CATEGORIES: [{cat: 'Men'}, {cat: 'Women'}],
  PLAYER_POSITIONS: [{pos: 'Outside Hitter', val: 'OH'},
                      {pos: 'Setter', val: 'S'},
                      {pos: 'Middle Blocker', val: 'MB'},
                      {pos: 'Libero', val: 'L'},
                      {pos: 'Opposite', val: 'O'},
                      {pos: 'Any', val: 'ANY'}]
}